### ISSUE TITLE
No way to teleport players back to their Islands

### ISSUE THREAD

**Issue by lachian** [FTBTeam/Team-Islands#5]
Pack: FTB Sky Adventures
Version: 1.0.0

When players die, and they had not changed their spawnpoint via sleeping in a bed, they do not spawn back on their islands, they spawn at world spawn. If they had not created a /home via FTBU, or have another teammate still at their island, I can't find a way to teleport them back to their island.

Is there a way to teleport players back to their island?

**Comment by Magesw** [comment]
NBTEditor can show you where their island is and you can set their pos that way or update to 1.1.0 even though it says on that version they need a permission to use it, hopefully adding said perm to ranks file works.

**Comment by Magesw** [comment]
> Where in their player's NBT is it? And what command are you talking about?

They added a command in v1.1.0 /teamislands myisland it is supposed to bring you back to your island but it doesn't work.

As to where in the players NBT I would have to look again, it's very late here will look it up later. Could always just ask the player if they have coords to it themselves or have died near it and have a coord to that.

**Comment by LatvianModder** [comment]
Doesn't work? Are you sure, because all myisland issues were fixed in .13

**Comment by Magesw** [comment]
> Doesn't work? Are you sure, because all myisland issues were fixed in .13

Yeah not saying it doesn't work in the newest team island update but the current Released version of Sky adventures is 1.1.0 and we are discussing that version and in that version teamislands is .12
